INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (1, 'Bruno', 'Pequeno', 'dog@30', 'bru@gmail.com', 1.78, 76, 'GAIN_MUSCULAR_MASS', 'ECTOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (2, 'Maria', 'Silva', 'pass123', 'maria@gmail.com', 1.65, 60, 'LOSE_WEIGHT', 'MESOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (3, 'João', 'Santos', 'securePwd', 'joao@gmail.com', 1.75, 85, 'GAIN_MUSCULAR_MASS', 'ENDOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (4, 'Carla', 'Ribeiro', 'mypassword', 'carla@gmail.com', 1.60, 55, 'MAINTAIN_HEALTH', 'ECTOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (5, 'Pedro', 'Ferreira', 'pass456', 'pedro@gmail.com', 1.82, 78, 'MAINTAIN_HEALTH', 'MESOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (6, 'Ana', 'Costa', 'secret123', 'ana@gmail.com', 1.68, 62, 'GAIN_MUSCULAR_MASS', 'MESOMORPH');
INSERT INTO tb_users (ID_user, first_name, last_name, password_user, email, height, weight, goals, biotype) VALUES (7, 'Ricardo', 'Oliveira', 'pwd1234', 'ricardo@gmail.com', 1.75, 80, 'LOSE_WEIGHT', 'ECTOMORPH');

INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (1,'Batata','Batatas são uma ótima fonte de potássio, um nutriente que ajuda a equilibrar o organismo e diminuir a pressão sanguínea, protegendo o coração e diminuindo os riscos de derrame. Além disso, as fibras e', 52,1.6, 80,'ferro, fósforo, magnésio e potássio','vitamina C, complexo B, niacina, tiamina e vitamina B6', 'AMOUNT', 0, 'https://unlockways3.blob.core.windows.net/unlockway-images/potatos.png');
INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (2,'Leite desnatado', 'O leite é uma fonte de cálcio e proteína. É uma bebida comum em muitas dietas.', 42, 3.4, 88, 'cálcio', 'vitamina D', 'MILILITERS', 1.0, 'https://unlockways3.blob.core.windows.net/unlockway-images/skimmed_milk.png');
INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (3,'Farinha de Trigo', 'A farinha de trigo é usada para fazer pães, bolos e massas. É uma fonte de carboidratos.', 364, 10, 11, 'ferro e magnésio', 'vitamina B1, vitamina B3', 'GRAMS', 1, 'https://unlockways3.blob.core.windows.net/unlockway-images/wheat_flour.png');
INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (4,'Açúcar', 'O açúcar é usado para adoçar alimentos e bebidas. Deve ser consumido com moderação.', 387, 0, 1, '-', '-', 'GRAMS', 0, 'https://unlockways3.blob.core.windows.net/unlockway-images/sugar.png');
INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (5,'Espinafre', 'O espinafre é rico em ferro, folato e antioxidantes. É um vegetal saudável para incluir em sua dieta.', 23, 2.9, 91, 'ferro e magnésio', 'vitamina A, vitamina K', 'GRAMS', 0.4, 'https://unlockways3.blob.core.windows.net/unlockway-images/spinach.png');
INSERT INTO tb_foods(ID_Food, name, description, calories, proteins, water, minerals, vitamins, measure, fats, photo) VALUES (6,'Iogurte', 'O iogurte é uma fonte de proteína e cálcio. Ele também contém probióticos que são bons para a saúde intestinal.', 61, 3.5, 88, 'cálcio', 'vitamina D, vitamina B12', 'MILILITERS', 1.5, 'https://unlockways3.blob.core.windows.net/unlockway-images/yogurt.png');

